#!/usr/bin/env node
/**
 * Single source of truth for environment variables.
 *
 * You edit ONE file — the root `.env` — and this script generates the
 * per-package files the toolchains insist on reading from their own dirs:
 *
 *   .env  ──►  frontend/.env.local   (read by Next.js)
 *         ──►  backend/.env          (read by the Firebase Functions CLI)
 *
 * Firebase browser config (NEXT_PUBLIC_FIREBASE_*) and the server-only
 * FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 secret are intentionally NOT passed
 * through to the frontend — the browser never connects to Firebase or
 * Firestore directly (see firebase/firestore.rules, backend/CLAUDE.md).
 * TideCloak is the only authentication provider, and any future Firestore
 * access happens server-side, in the backend, after the TideCloak auth
 * middleware has verified and authorized the request.
 *
 * Run via: pnpm run env:sync   (also runs automatically before `pnpm run dev`)
 */
'use strict'

const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const envPath = path.join(root, '.env')

if (!fs.existsSync(envPath)) {
  console.error(
    '\x1b[31mNo .env file found at the repo root.\x1b[0m\n' +
      'Create it first:  cp .env.example .env\n' +
      'See docs/ENV-VARS.md for what each variable is.'
  )
  process.exit(1)
}

/** Minimal .env parser — KEY=VALUE lines, # comments, no multiline values. */
function parseEnv(content) {
  const vars = {}
  for (const line of content.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq === -1) continue
    const key = trimmed.slice(0, eq).trim()
    let value = trimmed.slice(eq + 1).trim()
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }
    vars[key] = value
  }
  return vars
}

const env = parseEnv(fs.readFileSync(envPath, 'utf8'))
const get = (key) => env[key] ?? ''

const header = (target) =>
  `# GENERATED by scripts/sync-env.js — do not edit this file.\n` +
  `# Edit the root .env instead, then run: pnpm run env:sync\n` +
  `# (${target})\n\n`

// ── frontend/.env.local ──────────────────────────────────────────────
// All NEXT_PUBLIC_* keys pass through as-is, EXCEPT NEXT_PUBLIC_FIREBASE_* —
// Firebase Authentication is not used, and the frontend has no Firebase
// client SDK to configure. FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 is a
// server-only secret and is never written to a frontend file.
const frontendLines = [header('read by Next.js')]

for (const [key, value] of Object.entries(env)) {
  if (key.startsWith('NEXT_PUBLIC_') && !key.startsWith('NEXT_PUBLIC_FIREBASE_')) {
    frontendLines.push(`${key}=${value}`)
  }
}

// ── backend/.env ─────────────────────────────────────────────────────
// FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 is optional here — only needed for
// local development against a real Firestore project. Deployed Cloud
// Functions use Application Default Credentials instead (see
// backend/src/lib/firebase.ts) and do not read this variable.
const backendLines = [
  header('read by the Firebase Functions CLI'),
  `FIREBASE_SERVICE_ACCOUNT_KEY_BASE64=${get('FIREBASE_SERVICE_ACCOUNT_KEY_BASE64')}`,
  `CORS_ORIGIN=${get('CORS_ORIGIN')}`,
  `PORT=${get('PORT')}`,
  `CLIENT_ADAPTER=${get('CLIENT_ADAPTER')}`,
]

fs.writeFileSync(path.join(root, 'frontend', '.env.local'), frontendLines.join('\n') + '\n')
fs.writeFileSync(path.join(root, 'backend', '.env'), backendLines.join('\n') + '\n')

console.log('env:sync  .env → frontend/.env.local, backend/.env')
